name: first challenge

on: [push]

jobs:
  job1:
    name: Ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date
  job2:
    name: Windows job
    runs-on: windows-latest
    steps:
      - name: Date
        run: date
  #job3:
  #job4: